### ISSUE TITLE
Error when installing `tree-sitter-solidity` using pip

### ISSUE THREAD

**Issue by michprev** [JoranHonig/tree-sitter-solidity#37]
Hello,
thank you for developing this project! Cannot wait to try it out.

Unfortunately, I have a problem installing the `tree-sitter-solidity` package using pip.

`pip install tree-sitter-solidity` gives me the following error:
```
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [10 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-e3_922no/tree-sitter-solidity_87b7817e01434795a1c8d48a24aab32d/setup.py", line 12, in <module>
          requirements = [x for x in map(str.strip, REQUIREMENTS.read_text().split("\n")) if x != ""]
        File "/usr/lib/python3.10/pathlib.py", line 1134, in read_text
          with self.open(mode='r', encoding=encoding, errors=errors) as f:
        File "/usr/lib/python3.10/pathlib.py", line 1119, in open
          return self._accessor.open(self, mode, buffering, encoding, errors,
      FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-install-e3_922no/tree-sitter-solidity_87b7817e01434795a1c8d48a24aab32d/requirements.txt'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

**Comment by JoranHonig** [comment]
I think I messed up w/ the package, I'll see if I can fix it 👍

**Comment by JoranHonig** [comment]
Fixed it!

This is still experimental btw, planning on shipping some upgrades to the typed wrapper
